[[plugins]]
repo = 'preservim/nerdtree'
on_path = '/'
hook_add = '''
let NERDTreeShowHidden=1
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
'''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
    let g:vimtex_compiler_latexmk = {
        \ 'options' : [
	\   '-shell-escape',
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}

    let g:vimtex_compiler_latexmk_engines = {
        \ '_'                : '-xelatex',
        \}
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['puml', 'plantuml']

[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
depends = ['open-browser.vim']
on_ft = ['puml', 'plantuml']
